name: Build, Export, Upload Docs

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: write

    steps:
    - uses: actions/checkout@v3

    # Setup AWS Credentials

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-region: us-east-1
        role-to-assume: arn:aws:iam::451738990703:role/BradleyLymanPhotographyGithubAction
        role-session-name: BradleyLymanPhotographyBuild

    - name: Setup Node 18
      uses: actions/setup-node@v3
      with:
        node-version: 18.15.0

    # Build Website

    - name: Website Cache
      uses: actions/cache@v3
      with:
        path: node_modules
        key: ${{ runner.os }}-cargo-${{ hashFiles('**package-lock.json') }}

    - name: Website Build
      run: npm run build

    # Deploy

    - name: Deploy Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist


